### ISSUE TITLE
libtk8.6.so error at import

### ISSUE THREAD

**Issue by dmalt** [neuropycon/graphpype#3]
On my archlinux after installation 
```python
import graphpype
```
results into
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
after installing tk package this issue was resolved.
tk dependency should be added to dependencies list in installation instruction. 
Does it work on ubuntu out of the box?

**Comment by annapasca** [comment]
I didn't have this kind of error on ubuntu.
